services:
  db:
    container_name: ecommerce_db
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=A65sdec&21MnnsD
      - POSTGRES_USER=adminBreno3113
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
